### ISSUE TITLE
Suggestion for Test

### ISSUE THREAD

**Issue by breadoliveoilsalt** [learn-co-curriculum/ransom-note#2]
Hi.  Small comment: the following line in the test file kept throwing errors for me, no matter what my code looked like:

`let functionResult = buildHistogram(magazine)`

`buildHistogram` was no where else in the test file.  Perhaps the line should be:

`let functionResult = binaryMatch(magazine)` ?

Thanks.

**Comment by rrcobb** [comment]
I think this should be addressed by #1
